export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const NAV_TOGGLE = 'NAV_TOGGLE';
export const MODAL_CLOSE = 'MODAL_CLOSE';
export const MODAL_OPEN = 'MODAL_OPEN';

export const SAVE_RECEPIE_SUCCESS = 'SAVE_RECEPIE_SUCCESS';
export const SAVE_RECEPIE_FAIL = 'SAVE_RECEPIE_FAIL';

export const FETCH_RECEPIES_SUCCESS = 'FETCH_RECEPIES_SUCCESS';
export const FETCH_RECEPIES_START = 'FETCH_RECEPIES_START';
export const FETCH_RECEPIES_FAIL = 'FETCH_RECEPIES_FAIL';